### ISSUE TITLE
Use environment variables in Shoko container

### ISSUE THREAD

**Issue by SuperFlue** [ShokoAnime/ShokoServer#706]
To make it easier to configure Shoko when setting up the container, it would be nice if we had the ability to set some config options beforehand.

The main thing i am thinking about is the possibility to define the database server and credentials before launching.

This would make it possible to create a docker-compose with a MySQL db (or whatever variant you prefer) and Shoko in one go without having to change Shoko's config file after it has started once.

**Comment by Cazzar** [comment]
Done, will be in next daily.
This can be done with
```yml

version: "3"
services:
  shokoserver:
    container_name: shokoserver
    image: cazzar/shokoserver:daily
    ports:
      - 8111:8111
    volumes:
      - /example/vol
    environment: 
      - SHOKO_MySQL_Hostname=db
      - SHOKO_MySQL_SchemaName=shoko_linux
      - SHOKO_MySQL_Username=shoko
      - SHOKO_MySQL_Password=example
    links:
      - mariadb:db
    depends_on:
      - mariadb
    environment:
      - PUID=1000
      - PGID=100
    restart: unless-stopped
```
