### ISSUE TITLE
Retry connecting to database when starting

### ISSUE THREAD

**Issue by Dexil123** [ShokoAnime/ShokoServer#790]
So when I reboot my system I always have to restart the Shoko server because the database wasn't available yet when Shoko started. 
So it would be nice if Shoko server could try to start again after an preset interval.

**Comment by da3dsoul** [comment]
You can trigger it via api

**Comment by Dexil123** [comment]
Yeah, but can it be automated? Now I need to remember every time I reboot I have restart Shoko.
Running on Docker btw.

**Comment by Cazzar** [comment]
You can just use docker-compose and use
https://docs.docker.com/compose/compose-file/#depends_on

**Comment by Dexil123** [comment]
I have tried depends on but it doesn't wait until the database is ready. So Shoko is still starting right after it the database container is running but the database is not accessible yet.  
See also:
[https://docs.docker.com/compose/startup-order/](url)
"However, for startup Compose does not wait until a container is “ready” (whatever that means for your particular application) - only until it’s running.  "

**Comment by krbrs** [comment]
Just found this and hope this will be helpful even if the last post is from Feb 2021.

For Shoko I use this in my compose file:

```
    depends_on:
      mariadb:
        condition: service_healthy
```

For the DB i added a custom healthcheck so it actually returns a healthy status when it's up:

```
    healthcheck:
      test: "/usr/bin/mysql --user=<youruser> --password=<yourpassword> --execute \"SHOW DATABASES;\""
      start_period: 1m
      interval: 30s
      timeout: 2s
      retries: 5
```

maybe you can work with this for your compose file
